version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Подключаем модель
    depends_on:
      - db
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - api
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: berries
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
