version: '3.9'

services:
  api:
    build:
      context: ../
      dockerfile: services/Dockerfile.api
    image: berry_api_image:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - api_logs:/logs

  bot:
    build:
      context: ../
      dockerfile: services/Dockerfile.bot
    env_file:
      - .env
    image: berry_bot_image:latest
    depends_on:
      - api
    restart: always
    volumes:
      - bot_logs:/logs

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  api_logs:
  bot_logs:
