FROM python:3.12-slim

WORKDIR /bot

COPY services/telegram_bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/telegram_bot/ .
COPY services/database/ ./services/database/

CMD ["python", "bot.py"]
