name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy project to server via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ root@185.250.44.67:/home/bakhasimf/apps

      - name: Rebuild & Restart Docker on server
        run: |
          ssh root@185.250.44.67 << 'EOF'
          cd /home/bakhasimf/apps
          docker compose down
          docker compose up -d --build
          EOF
