name: Build and Deploy Berry Classifier

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        run: docker build -f services/Dockerfile.api -t berry_api_image .

      - name: Build Bot image
        run: docker build -f services/Dockerfile.bot -t berry_bot_image .

      - name: Save Docker images to tar
        run: |
          docker save berry_api_image > berry_api_image.tar
          docker save berry_bot_image > berry_bot_image.tar

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
          
      - name: Clean up old .tar files on server
        run: |
          ssh -o StrictHostKeyChecking=no root@185.250.44.67 'rm -f /root/home/bakhasimf/apps/berry_classifier/*.tar'
          
      - name: Copy project and images to server
        run: |
          scp -o StrictHostKeyChecking=no berry_api_image.tar berry_bot_image.tar root@185.250.44.67:/root/home/bakhasimf/apps/berry_classifier/
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ root@185.250.44.67:/root/home/bakhasimf/apps/berry_classifier/

      - name: Load images and restart Docker Compose
        run: |
          ssh root@185.250.44.67 << 'EOF'
          docker load < /root/home/bakhasimf/apps/berry_classifier/berry_api_image.tar
          docker load < /root/home/bakhasimf/apps/berry_classifier/berry_bot_image.tar
          cd /root/home/bakhasimf/apps/berry_classifier
          docker-compose down
          docker-compose up -d
          docker system prune -af --volumes
          EOF
