name: Build and Deploy Berry Classifier

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Clean up old files on server
        run: |
          ssh -o StrictHostKeyChecking=no root@185.250.44.67 '
            cd /root/home/bakhasimf/apps/berry_classifier &&
            ls | grep -v "^logs$" | xargs rm -rf
          '
      - name: Copy necessary files to server
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./services \
            ./models \
            ./logging_config.yaml \
            ./logs/api.log \
            ./logs/bot.log \
            root@185.250.44.67:/root/home/bakhasimf/apps/berry_classifier/

      - name: Build and run containers on server
        run: |
          ssh root@185.250.44.67 << 'EOF'
          cd /root/home/bakhasimf/apps/berry_classifier/
          
          docker build -f services/Dockerfile.api -t berry_api_image:latest .
          docker build -f services/Dockerfile.bot -t berry_bot_image:latest .
          
          docker-compose -f services/docker-compose.yml down
          docker-compose -f services/docker-compose.yml up -d --build --force-recreate --remove-orphans
          docker system prune -af --volumes
          
          EOF
